development:
  adapter: postgresql
  encoding: unicode
  database: iwitness_development
  pool: 5
  username: kriss
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: whatsat_production
  pool: 5
  password: